spring:
  zookeeper:
    quorum: twdp-nn1
    port: 2181

crawler:
  start-urls:
    - start-url: http://data.stats.gov.cn/easyquery.htm
      indexer-type: kafka
      http-method: POST
      headers:
        content-type: application/x-www-form-urlencoded
      encode: ISO-8859-1
      data-template: 'id=zb&dbcode=hgyd&wdcode=zb&m=getTree'
      pagination:
        no-pagination: true
        stop-when-all-links-crawled: true
      links:
        new-links-only: true
        http-method: GET
        url-template: http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=${db}&rowcode=${rowcode}&colcode=${colcode}&wds=${wds}&dfwds=${dfwds}&k1=1563764645856
        headers:
          content-type: application/json

wrappers:
  websites:
    - website: data.stats.gov.cn
      match-url: .*QueryData.*

indexers:
  - indexer-type: kafka
    cluster-nodes: twdp-dn5:9092,twdp-dn4:9092,twdp-dn3:9092
    index: crawler

logging:
  level:
    me.yingrui: DEBUG