spring:
  hadoop:
    config:
      fs:
        defaultFS: hdfs://192.168.56.101:8020
  zookeeper:
    quorum: 192.168.56.101
    port: 2181

crawler:
  start-urls:
    - start-url: https://www.infoq.cn/public/v1/article/getList
      url: https://www.infoq.cn/
      http-method: POST
      headers:
        referer: https://www.infoq.cn/topic/cloud-computing
        content-type: application/json
      body-template: '{"type": 1, "size": 12, "score": 1519120800000}'
      pagination:
        path: data[-1:].score
        prefix: https://www.infoq.cn/?score=
        url-template: https://www.infoq.cn/public/v1/article/getList
        body-template: '{"type": 1, "size": 12, "score": [(${src})]}'
      links:
        path: data[*].uuid
        prefix: https://www.infoq.cn/article/
        http-method: POST
        url-template: https://www.infoq.cn/public/v1/article/getDetail
        headers:
          content-type: application/json
          referer: '[(${url})]'
        body-template: '{"uuid":"[(${src})]"}'

logging:
  level:
    me.yingrui: DEBUG