spring:
  hadoop:
    config:
      fs:
        defaultFS: hdfs://192.168.56.101:8020
  zookeeper:
    quorum: 192.168.56.101
    port: 2181

crawler:
  start-urls:
    - start-url: https://www.infoq.cn/public/v1/article/getList
      url: https://www.infoq.cn/
      http-method: POST
      headers:
        referer: https://www.infoq.cn/topic/cloud-computing
        content-type: application/json
      body-template: '{"type": 1, "size": 12}'
      pagination:
        path: data[-1:].score
        prefix: https://www.infoq.cn/?score=
        url-template: https://www.infoq.cn/public/v1/article/getList
        body-template: '{"type": 1, "size": 12, "score": [(${src})]}'
      links:
        path: data[*].uuid
        prefix: https://www.infoq.cn/article/
        http-method: POST
        url-template: https://www.infoq.cn/public/v1/article/getDetail
        headers:
          content-type: application/json
          referer: '[(${url})]'
        body-template: '{"uuid":"[(${src})]"}'

wrapper:
  extractors:
    - field: title
      path: data.article_title
    - field: publish_time
      path: data.publish_time
      type: datetime
      extractor: DatetimeExtractor
    - field: summary
      path: data.article_summary
    - field: views
      path: data.views
    - field: author
      path: data.author[*].nickname
      type: array
    - field: translator
      path: data.translator[*].nickname
      type: array
    - field: topic
      path: data.topic[*].name
      type: array
    - field: content
      path: data.content
      extractor: HtmlContentExtractor

indexer:
  cluster-nodes: localhost:9300
  cluster-name: yingrui-laptop
  index: article
  type: _doc
  string-fields: topic, author, translator


logging:
  level:
    me.yingrui: DEBUG