spring:
  zookeeper:
    quorum: twdp-nn1
    port: 2181

crawler:
  start-urls:
    - start-url: https://www.infoq.cn/public/v1/article/getList
      indexer-type: ElasticSearch
      url: https://www.infoq.cn/
      http-method: POST
      headers:
        referer: https://www.infoq.cn/topic/cloud-computing
        content-type: application/json
      data-template: '{"type": 1, "size": 12}'
      pagination:
        no-pagination: false
        stop-when-all-links-crawled: true
        path: data[-1:].score
        prefix: https://www.infoq.cn/?score=
        url-template: https://www.infoq.cn/public/v1/article/getList
        body-template: '{"type": 1, "size": 12, "score": [(${src})]}'
      links:
        new-links-only: true
        path: data[*].uuid
        prefix: https://www.infoq.cn/article/
        http-method: POST
        url-template: https://www.infoq.cn/public/v1/article/getDetail
        headers:
          content-type: application/json
          referer: '[(${url})]'
        body-template: '{"uuid":"[(${src})]"}'
    - start-url: https://insights.thoughtworks.cn/
      indexer-type: ElasticSearch
      pagination:
        no-pagination: false
        stop-when-all-links-crawled: true
        path: a.next
      links:
        new-links-only: true
        path: .entry-title a
    - start-url: http://data.stats.gov.cn/easyquery.htm
      indexer-type: kafka
      http-method: POST
      headers:
        content-type: application/x-www-form-urlencoded
      encode: ISO-8859-1
      data-template: 'id=zb&dbcode=hgyd&wdcode=zb&m=getTree'
      pagination:
        no-pagination: true
        stop-when-all-links-crawled: true
      links:
        new-links-only: true
        http-method: GET
        url-template: http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=${db}&rowcode=${rowcode}&colcode=${colcode}&wds=${wds}&dfwds=${dfwds}&k1=1563764645856
        headers:
          content-type: application/json

wrappers:
  websites:
    - website: www.infoq.cn
      match-url: https://www.infoq.cn/article/.*
      extractors:
        - field: title
          path: data.article_title
        - field: publish_time
          path: data.publish_time
          type: datetime
          extractor: DatetimeExtractor
        - field: summary
          path: data.article_summary
        - field: views
          path: data.views
        - field: author
          path: data.author[*].nickname
          type: array
        - field: translator
          path: data.translator[*].nickname
          type: array
        - field: topic
          path: data.topic[*].name
          type: array
        - field: content
          path: data.content
          extractor: HtmlContentExtractor
    - website: insights.thoughtworks.cn
      match-url: https://insights.thoughtworks.cn/.*
      not-match-url: https://insights.thoughtworks.cn/page/.*
      extractors:
        - field: title
          path: h1.entry-title
        - field: publish_time
          path: time.entry-time
          type: datetime
          extractor: DatetimeExtractor
        - field: author
          path: a[rel=author] span
          type: array
        - field: topic
          path: a[rel=tag]
          type: array
        - field: content
          path: div.entry-content
    - website: data.stats.gov.cn
      match-url: .*QueryData.*

indexers:
  - indexer-type: ElasticSearch
    cluster-nodes: 172.30.3.211:30001
    cluster-name: elasticsearch-cluster
    index: article
    type: _doc
    string-fields: topic, author, translator, website
  - indexer-type: kafka
    cluster-nodes: twdp-dn5:9092,twdp-dn4:9092,twdp-dn3:9092
    index: crawler


logging:
  level:
    me.yingrui: DEBUG