spring:
  hadoop:
    config:
      fs:
        defaultFS: hdfs://192.168.56.101:8020
  zookeeper:
    quorum: 192.168.56.101
    port: 2181

crawler:
  start-urls:
    - start-url: https://insights.thoughtworks.cn/
      url: https://insights.thoughtworks.cn/
      pagination:
        no-pagination: false
        stop-when-all-links-crawled: true
        path: a.next
      links:
        new-links-only: true
        path: .entry-title a

wrappers:
  websites:
    - website: insights.thoughtworks.cn
      matched-url: https://insights.thoughtworks.cn/.*
      not-matched-url: https://insights.thoughtworks.cn/page/.*
      extractors:
        - field: title
          path: data.article_title
        - field: publish_time
          path: data.publish_time
          type: datetime
          extractor: DatetimeExtractor
        - field: summary
          path: data.article_summary
        - field: views
          path: data.views
        - field: author
          path: data.author[*].nickname
          type: array
        - field: translator
          path: data.translator[*].nickname
          type: array
        - field: topic
          path: data.topic[*].name
          type: array
        - field: content
          path: data.content
          extractor: HtmlContentExtractor

indexer:
  cluster-nodes: localhost:9300
  cluster-name: yingrui-laptop
  index: article
  type: _doc
  string-fields: topic, author, translator


logging:
  level:
    me.yingrui: DEBUG