spring:
  hadoop:
    config:
      fs:
        defaultFS: hdfs://192.168.56.101:8020
  zookeeper:
    quorum: 192.168.56.101
    port: 2181

crawler:
  start-urls:
    - start-url: https://www.infoq.cn/public/v1/article/getList
      http-method: POST
      headers:
        referer: https://www.infoq.cn/topic/cloud-computing
        content-type: application/json
      body: '{"type": 1, "size": 1}'
      links:
        path: data[*].uuid
        prefix: https://www.infoq.cn/article/
        http-method: POST
        url-template: https://www.infoq.cn/public/v1/article/getDetail
        headers:
          content-type: application/json
          referer: '[(${url})]'
        body-template: '{"uuid":"[(${src})]"}'

