spring:
  zookeeper:
    quorum: twdp-nn1
    port: 2181

crawler:
  start-urls:
    - start-url: http://data.stats.gov.cn/easyquery.htm
      http-method: POST
      headers:
        content-type: application/x-www-form-urlencoded
      encode: ISO-8859-1
      data-template: 'id=zb&dbcode=hgyd&wdcode=zb&m=getTree'
#      data-template: 'id=${id}&dbcode=${dbcode}&wdcode=${wdcode}&m=getTree'
      pagination:
        no-pagination: true
        stop-when-all-links-crawled: true
      links:
        new-links-only: true
        http-method: GET
        url-template: http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=${db}&rowcode=${rowcode}&colcode=${colcode}&wds=${wds}&dfwds=${dfwds}&k1=1563764645856
        headers:
          content-type: application/json

wrappers:
  websites:
    - website: data.stats.gov.cn
      match-url: .*QueryData.*

indexer:
  cluster-nodes: 172.30.3.211:30001
  cluster-name: elasticsearch-cluster
  index: article
  type: _doc
  string-fields: topic, author, translator, website


logging:
  level:
    me.yingrui: DEBUG