spring:
  zookeeper:
    quorum: 192.168.56.101
    port: 2181

crawler:
  start-urls:
    - start-url: https://insights.thoughtworks.cn/
      pagination:
        no-pagination: false
        stop-when-all-links-crawled: true
        path: a.next
      links:
        new-links-only: true
        path: .entry-title a

wrappers:
  websites:
    - website: insights.thoughtworks.cn
      match-url: https://insights.thoughtworks.cn/.*
      not-match-url: https://insights.thoughtworks.cn/page/.*
      extractors:
        - field: title
          path: h1.entry-title
        - field: publish_time
          path: time.entry-time
          type: datetime
          extractor: DatetimeExtractor
        - field: author
          path: a[rel=author] span
          type: array
        - field: topic
          path: a[rel=tag]
          type: array
        - field: content
          path: div.entry-content

indexer:
  cluster-nodes: localhost:9300
  cluster-name: yingrui-laptop
  index: article
  type: _doc
  string-fields: topic, author, translator, website


logging:
  level:
    me.yingrui: DEBUG